config/routes.rb
Rails.application.routes.draw do
  resources :messages 

  resources :groups do 
    member do
      post 'join'
      get 'groupmessage'
    end
  end

  resources :stuffs do
    member do
       get 'borrowrequest'
    end
  end

  get 'sessions/new'

  get 'users/new'

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root :to => "sessions#new"
get "users/own_page"

resources :users 
resources :sessions

end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
	belongs_to :user
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :set_stuff, only: [:show, :edit, :update, :destroy]

  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = Stuff.all
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
  end

  # GET /stuffs/new
  def new
    @stuff = Stuff.new
  end

  # GET /stuffs/1/edit
  def edit
  end

   def borrowrequest
     @stuff = Stuff.find(params[:id])
     @message = Message.new
     @message.content = "Someone wants to borrow your item!"
     @message.sender_id = current_user.id
     @message.stuff_id = @stuff.id
     @message.save
     @stuff.user.messages << @message

     respond_to do |format|
      if @message.save
        format.html { redirect_to root_url, notice: 'Borrow request sent!' }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :show }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
     end
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(stuff_params)
    @stuff.user = current_user
    @stuff.borrowed = false

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to root_url, notice: 'Stuff was successfully created.' }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :new }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1
  # PATCH/PUT /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to @stuff, notice: 'Stuff was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    @stuff.destroy
    respond_to do |format|
      format.html { redirect_to stuffs_url, notice: 'Stuff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuff
      @stuff = Stuff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuff_params
      params.require(:stuff).permit(:name, :user_id, :borrowed)
    end
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/stuffs/_form.html.erb
<%= form_for(@stuff) do |f| %>
  <% if @stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stuff.errors.count, "error") %> prohibited this stuff from being saved:</h2>

      <ul>
      <% @stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stuffs/edit.html.erb
<h1>Editing stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @stuff %> |
<%= link_to 'Back', stuffs_path %>

app/views/stuffs/index.html.erb
<h1>Listing stuffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Borrowed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stuffs.each do |stuff| %>
      <tr>
        <td><%= stuff.name %></td>
        <td><%= stuff.user_id %></td>
        <td><%= stuff.borrowed %></td>
        <td><%= link_to 'Show', stuff %></td>
        <td><%= link_to 'Edit', edit_stuff_path(stuff) %></td>
        <td><%= link_to 'Destroy', stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stuff', new_stuff_path %>

app/views/stuffs/new.html.erb
<h1>New stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', stuffs_path %>

app/views/stuffs/show.html.erb
<p id="notice"></p>

<h1> <%= @stuff.name %> </h1>
Owner: <%= @stuff.user.name %>
</br>
<% if @stuff.name == "car" %>
CO2 impact factor: 65t
<% end %>

<% if @stuff.name == "computer " %>
CO2 impact factor: 78kg
<% end %>

<div class="box">
Status: 
<% if @stuff.borrowed == false %>
Free to be borrowed!
<% else %>
Borrowed
<% end %>
</div>

</br>
<%if @stuff.borrowed == false %>
    <%= link_to "Make borrow request", borrowrequest_stuff_path(@stuff), :class=> "btn btn-primary" %> 
<% end %>

<% if current_user == @stuff.user %>
</br>
</br>
<%= link_to 'Edit', edit_stuff_path(@stuff) %>
<% end %>