config/routes.rb
Rails.application.routes.draw do
  resources :messages 

  resources :groups do 
    member do
      post 'join'
      get 'groupmessage'
    end
  end

  resources :stuffs do
    member do
       get 'borrowrequest'
    end
  end

  get 'sessions/new'

  get 'users/new'

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root :to => "sessions#new"
get "users/own_page"

resources :users 
resources :sessions

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :messages
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  def join 
    @group = Group.find(params[:id])
    @group.users << current_user
    #render :nothing => true
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'You joined to the group!' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :show }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end

  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  def groupmessage 
    @group = Group.find(params[:id])
    @message = Message.new
    @message.group = @group
    @message.sender_id = current_user.id
    @message.save
    @group.messages << @message
    #render 'app/views/messages/form'
    render :partial => 'messages/form', :formats => :html
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.users << current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id, :description, :message_id, :sender_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :size => "30x5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>All groups</h1>

<div class="col-md-9">
    <% @groups.each do |g| %>
        <%= link_to g.name, group_path(g), :class=> "btn btn-warning", :style => "padding:10px;" %> 
    <% end %>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="all">
<p id="notice"></p>

<h1> <%= @group.name %> </h1>

<%= @group.description %> 

<% if not @group.users.include?(current_user) %>
    <%= link_to "Join", join_group_path(@group), :class=> "btn btn-primary", :method => "post" %>
<% end %>

 <%= link_to "Write message", groupmessage_group_path(@group), :class=> "btn btn-primary" %> 

</br>



<div class="row">
<div class="col-md-4">
  <h2>Members</h2>
  <% @group.users.each do |f| %>
  <%= link_to f.name, user_path(f), :class=> "btn btn-warning" %> 
  <% end %>
</div>

<div class="col-md-4">
<h2>Stuffs</h2>
  <% @group.users.each do |f| %>
  <% f.stuffs.each do |s| %>
      <%= link_to s.name, stuff_path(s), :class=> "btn btn-warning" %>
  <% end %> 
  <% end %>
</div>
</div>

</div>

<script>

$('a[data-remote=true]').live('ajax:before', function () {
   if ($(this).attr('ajax-loading')) {
     return false;
   } else {
     $(this).attr('ajax-loading', true);
   }
}).live('ajax:complete', function () {
  $(this).removeAttr('ajax-loading');
});


</script>