config/routes.rb
Rails.application.routes.draw do
  resources :messages 

  resources :groups do 
    member do
      post 'join'
      get 'groupmessage'
    end
  end

  resources :stuffs do
    member do
       get 'borrowrequest'
    end
  end

  get 'sessions/new'

  get 'users/new'

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root :to => "sessions#new"
get "users/own_page"

resources :users 
resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base

  #attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  #belongs_to :group
  has_many :stuffs
  has_and_belongs_to_many :groups
  has_many :messages

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	  if current_user == nil
  	  	@user = User.new
      else
      	redirect_to root_url
      end

  end

  def show
      @user = User.find(params[:id])
  end


  def create
      @user = User.new(user_params)
      if @user.save
         redirect_to root_url, :notice => "Signed up!"
      else
          render "new"
      end
  end

  def own_page
  	  @user = current_user
      if @user =! nil
      	@user = current_user
      else
      	redirect_to root_url
      end
  end

   def user_params
      # It's mandatory to specify the nested attributes that should be whitelisted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
   end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/me.html.erb
Jeeeeeee

app/views/users/new.html.erb
<div class="all">
<% if current_user %>
Jee. 
asd


<% else %>

<div class="box">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</div>


<% end %>
</div>

app/views/users/own_page.html.erb
<div class="all">
<div class="row">

<div class="col-md-9">
<h2>Welcome. <small>Let's create common households.</small></h2>
</div>
<div class="col-md-3">
<%= link_to "My profile", user_path(current_user), :class=> "btn btn-primary pull-right", :style => "margin-right:10px;" %> 
</div>

</div>
</div>

<div class="col-md-4">
  <h2>Groups</h2>

  <% @current_user.groups.each do |f| %>

  <div class="box" style="float:left;"><%= link_to f.name, group_path(f), :class=> "btn btn-warning" %> </div>

  <% end %>
  <%= link_to "All groups", groups_path, :class=> "btn btn-mini" %>
  <%= link_to "Create new group", new_group_path, :class=> "btn btn-mini" %>

</div>
    
    <div class="col-md-4">
    <h2>My stuffs</h2>

    <% @current_user.stuffs.each do |f| %>

    <%= link_to f.name, stuff_path(f), :class=> "btn btn-warning" %> 

    <% end %>
    <%= link_to "Add new stuff", new_stuff_path, :class=> "btn btn-mini" %> 
    </div>

    <div class="col-md-4">
    	<h2>Messages</h2>
        <% @current_user.messages.each do |m| %>
            <% @se = User.find_by_id(m.sender_id) %>
            <%= link_to @se.name, user_path(@se) %> wants to borrow your
            <% @s = Stuff.find_by_id(m.stuff_id) %>
            <% if @s != nil %>
            <%= @s.name %>
            <% end %>
        </br>
        <% end %>
    </div>

app/views/users/show.html.erb
<div class="all">
<h1><%=@user.name %> </h1>
email: <%=@user.email %> 
</div>

</br>
<% @user.stuffs.each do |s| %>

<%= link_to s.name, stuff_path(s), :class => "btn btn-warning" %> 

<% end %>

</br>
<% if @user == current_user %>
<%= link_to 'Edit', edit_user_path(@user) %> 
<% end %>

app/views/users/view.html.erb
<div class="all">
<% if current_user %>
Jee. 



<% else %>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>



<% end %>
</div>